### ISSUE TITLE
Using AudioNodes instead of MediaStream

### ISSUE THREAD

**Issue by antoniocapelo** [Sambego/audio-effects#7]
Hi! Thanks for the lib!
Is it possible to create an `Input` node with other than a `MediaStream`?
I've read the src and in the `set` signature it accepts `AudioNode|MediaStream` but the `audioContext.createMediaStreamSource` function tha'ts called only accepts `MediaStream`s..

I'm using local audio files, so I think I'm 'stuck' with regular Audio Nodes, and cannot generate a stream with them... Is this feasible?

**Comment by Sambego** [comment]
Hey @antoniocapelo you could use the file reader API to read the local audio files and create a buffer source node from it.
